### ISSUE TITLE
Move to distroless image

### ISSUE THREAD

**Issue by kumarabd** [meshery/meshery-consul#130]

**Comment by mgfeller** [comment]
@kumarabd why is this a bug?

**Comment by kumarabd** [comment]
@mgfeller  sorry about that. Created in a hurry

**Comment by leecalcote** [comment]
The same needs done for other adapters. // @Aisuko

**Comment by Aisuko** [comment]
@leecalcote Any detail?

**Comment by kumarabd** [comment]
@Aisuko checkout istio adapter dockerfile

**Comment by acald-creator** [comment]
bump

Considering using Chainguard distroless image

**Comment by Aisuko** [comment]
Done https://github.com/meshery/meshery-consul/blob/81317eb2f2126d81fc9b2d44d65811adcb643ed2/Dockerfile#L20C1-L21C1
