### ISSUE TITLE
[CI] add error codes utility runner workflow

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery-consul#179]
**Current Behaviour**
Error codes utility runner workflow is not present.

**Desired Behavious**
Add the error codes utility runner workflow.

**Instructions in https://github.com/meshery/meshery-linkerd/issues/213**

**Comment by iamsdas** [comment]
I'd like to take up this issue

**Comment by amino19** [comment]
@iamsdas : Here you go! :rocket:
