### ISSUE TITLE
[CI] add label commenter workflow

### ISSUE THREAD

**Issue by amino19** [meshery/meshery-consul#194]
**Description:**

This repository should have the label commenter workflow.
It would run whenever an issue/pr is labelled with one of the targeted labels and comment down any relevant information.

**Contributor Reference:**

The workflow would use: https://github.com/peaceiris/actions-label-commenter

A sample workflow is defined in: https://github.com/meshery/meshery/blob/master/.github/workflows/label-commenter.yml.

It would also need a sample configuration which is defined in: https://github.com/meshery/meshery/blob/master/.github/label-commenter-config.yml

**NOTE:**

- In the above configuration https://github.com/meshery/meshery/blob/88d1c7c559259775ce2affab2a15a32c673c3f52/.github/label-commenter-config.yml#L26-L41 are specific to Meshery and won't be needed on every repository.
- Do comment in PR if you find any label is missing for the repo.

**Comment by warunicorn19** [comment]
@CypherpunkSamurai sure!

**Comment by amino19** [comment]
> > In the above configuration https://github.com/meshery/meshery/blob/88d1c7c559259775ce2affab2a15a32c673c3f52/.github/label-commenter-config.yml#L26-L41 are specific to Meshery and won't be needed on every repository.
> 
> So you mean this repo `meshery/meshery-consul` should not have https://github.com/meshery/meshery/blob/88d1c7c559259775ce2affab2a15a32c673c3f52/.github/label-commenter-config.yml#L26-L41 right?
> 
> > Do comment in PR if you find any label is missing for the repo.
> 
> I don't understand this line. Please kindly explain. Am i supposed to comment on the PR if it has no labels?

heya @CypherpunkSamurai, here's a [reference](https://github.com/service-mesh-performance/service-mesh-performance/pull/241).

1. Yes, this repository doesn't have `label-commenter.yml` inside workflows, so doesn't have config as well!
2. If any label you doesn't found here as dealing at [meshery](https://github.com/meshery/meshery/blob/master/.github/label-commenter-config.yml), _(absence here)_, feel free to inform us!
