### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by ShervinPlays** [meshery/meshery-consul#213]
**Current State:**

**Desired State:**

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
Is there any additional detail that you would like to add to this issue, @ShervinPlays?

**Comment by warunicorn19** [comment]
Issue seems stale with no details. Closing, for now, @ShervinPlays please feel free to reopen.
