### ISSUE TITLE
[CI] Update Slack.yml and add newcomer-alert workflow

### ISSUE THREAD

**Issue by cpepper96** [meshery/meshery-consul#217]
**Current Behavior**
Currently the slack.yml is outdated. Also there is no automated way of notifying the slack channel when a "good first issue" has been created.

**Desired Behavior**
Update slack.yml and add newcomer-alert.yml to the Github workflow. 

---
**Resources**
Add the updated slack.yml file and the newcomer-alert.yml file to the .github/workflow folder.

Files needed:
https://github.com/meshery/meshery-istio/blob/master/.github/workflows/slack.yml
https://github.com/layer5io/layer5/blob/master/.github/workflows/newcomers-alert.yml

**Comment by msaini0r** [comment]
@cpepper96 can you review this, please.

**Comment by msaini0r** [comment]
@cpepper96 I tried updating these both, but I don't know the tests are failing. Can you help me?

**Comment by cpepper96** [comment]
@msaini0r so it looks like your last PR passed all tests. The only thing I can think of is you might want to do two separate PR's for updating the shields and slack/newcomer yml. Did you close the PR or did someone else?
