### ISSUE TITLE
[Docs]The updation of shields is needed in README.md

### ISSUE THREAD

**Issue by Swapnil-Bhabal** [meshery/meshery-consul#218]
**Current State:**
Small updation of shields in README.md

![image](https://user-images.githubusercontent.com/61308713/146508649-7e5fa708-dcee-46bd-8144-71bdf2c71704.png)

**Desired State:**
This is how it should look like
![image](https://user-images.githubusercontent.com/61308713/146508697-71e7b202-f026-4450-8990-77851eb7da6e.png)

updation should be done in this README.md by keeping the shield style uniform to following meshery-istio's README.md :
https://github.com/meshery/meshery-istio/blob/721b78783182e65145cefde64d905dab3ca20ba1/README.md?plain=1#L13

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by msaini0r** [comment]
@Swapnil-Bhabal I would like to work on this.

**Comment by msaini0r** [comment]
@leecalcote We can close this issue now. Because I have solved this issue in another pr which already has been merged.
