### ISSUE TITLE
[Docs] Incorrect URL in the Github Repository for docs 

### ISSUE THREAD

**Issue by shivaylamba** [meshery/meshery-consul#224]
**Current State:**

![image](https://user-images.githubusercontent.com/19529592/146976981-63f41dcb-b133-4423-957c-953bb2f3000a.png)
Incorrect URL in the Github Repository for docs 
**Desired State:**

Correct url to be posted.
---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
Thank you for reporting this, @shivaylamba 👍

**Comment by leecalcote** [comment]
Link updated. ✔️
