### ISSUE TITLE
"Management" should be changed to "Lifecycle" in the instructions.

### ISSUE THREAD

**Issue by IMPranshu** [meshery/meshery-consul#226]
#### Current Behavior

The instructions seem to be wrong as there is no "Management" option to choose from as specified in the instructions.
#### Expected Behavior

Management should change to Lifecycle. There are many instances where an update of the instruction is required.

#### Screenshots/Logs
![Screenshot (226)_LI](https://user-images.githubusercontent.com/43396684/147867955-c25a8c52-4a99-411c-9d08-3238f24e67ff.jpg)
TDL4L01AR-F02SBNZ3ZRB-5874fdbde0

https://user-images.githubusercontent.com/43396684/147867979-ef4764a4-10b3-4941-98a1-27f816a98eac.mp4

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by asubedy** [comment]
Thank you @IMPranshu. Will you work on solving this issue?

**Comment by IMPranshu** [comment]
Yes absolutely

**Comment by asubedy** [comment]
Sure, here you go 🚀

**Comment by IMPranshu** [comment]
Thank you for the opportunity. Will try and solve this and others too.

**Comment by asubedy** [comment]
@IMPranshu, I just noticed you have opened this issue on a different repository. Could you please open this issue at the [service-mesh-labs repository](https://github.com/layer5io/service-mesh-labs)

The service-mesh-labs repo would be the one where you will be able to edit the instructions. Thank you. I will be closing this issue here.

**Comment by IMPranshu** [comment]
Ok, sure.
