### ISSUE TITLE
[CI] Displace BATS tests

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-consul#236]
At this point, we have abandoned the BATS test in favor of the new style integration tests. It's time to remove / replace those BATS tests.

_Originally posted by @leecalcote in https://github.com/meshery/meshery-consul/issues/235#issuecomment-1020489954_

**Comment by leecalcote** [comment]
@Revolyssup how's this coming along?

**Comment by Revolyssup** [comment]
https://github.com/meshery/meshery-consul/pull/256
