### ISSUE TITLE
Update to Meshery-adapter-library v0.5.2

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-consul#243]
#### Current Behavior
While updating this dependency, errors occurred.

#### Screenshots/Logs
```
meshery-consul git:(master) ✗ go get github.com/layer5io/meshery-adapter-library/adapter@v0.5.2
# github.com/layer5io/meshery-adapter-library/adapter
../go/pkg/mod/github.com/layer5io/meshery-adapter-library@v0.5.2/adapter/oam.go:194:40: not enough arguments in call to manifests.GetFromManifest
        have (string, number, manifests.Config)
        want (context.Context, string, int, manifests.Config)
../go/pkg/mod/github.com/layer5io/meshery-adapter-library@v0.5.2/adapter/oam.go:196:36: not enough arguments in call to manifests.GetFromHelm
        have (string, number, manifests.Config)
        want (context.Context, string, int, manifests.Config)
../go/pkg/mod/github.com/layer5io/meshery-adapter-library@v0.5.2/adapter/oam.go:267:40: not enough arguments in call to manifests.GetFromManifest
        have (string, number, manifests.Config)
        want (context.Context, string, int, manifests.Config)
../go/pkg/mod/github.com/layer5io/meshery-adapter-library@v0.5.2/adapter/oam.go:269:36: not enough arguments in call to manifests.GetFromHelm
        have (string, number, manifests.Config)
        want (context.Context, string, int, manifests.Config)
```

#

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Revolyssup** [comment]
@leecalcote  this is due to older meshkit. Meshkit and adapter-library need to be updated together

**Comment by leecalcote** [comment]
Oh, I see. Ok that makes sense.
