### ISSUE TITLE
Could not create a pathset for static component generation

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-consul#261]
#### Current Behavior

```
➜  meshery-consul git:(master) make run
go mod tidy;
DEBUG=true go run main.go
INFO[2022-04-25T14:09:31-05:00] KUBECONFIG: /Users/lee/.meshery/kubeconfig.yaml  app=consul-adapter
INFO[2022-04-25T14:09:31-05:00] Adaptor Listening at port: 10002              app=consul-adapter
INFO[2022-04-25T14:09:31-05:00] Registering static workloads...               app=consul-adapter
INFO[2022-04-25T14:09:31-05:00] Registering latest workload components for version edge  app=consul-adapter
INFO[2022-04-25T14:09:31-05:00] Components available statically for version v0.43.0. Skipping dynamic component registeration  app=consul-adapter
ERRO[2022-04-25T14:09:31-05:00] lstat /Users/lee/code/meshery-consul/templates/oam/traits: no such file or directory  app=consul-adapter code=1004 probable-cause= severity=2 short-description="Could not create a pathset for static component generation" suggested-remediation=
```

#### Environment

- **Host OS:** Mac 
- **Platform:** Local
- **Meshery Server Version:** stable-v0.6.0-rc.5p
- **Meshery Client Version:** stable-v
- **Meshery Adapter Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Revolyssup I'm still seeing this error.

**Comment by acald-creator** [comment]
@leecalcote Do you still see this issue?

I didn't see this when I was updating this repo to 1.19

**Comment by acald-creator** [comment]
we moved to use meshmodels, so traits wouldn't exist anymore
