### ISSUE TITLE
[CI] update go version in ci.yml

### ISSUE THREAD

**Issue by cpepper96** [meshery/meshery-consul#262]
#### Current Behavior
All meshery adapters use go version 1.17 now, the ci.yml file needs to be updated to reflect this.

#### Desired Behavior
Update the go version to 1.17 in the ci.yml file.

#### Implementation
You can find the outdated version [here](https://github.com/meshery/meshery-consul/blob/78da7fb74a2c5f1b112dd001239b692951e6bc38/.github/workflows/ci.yml#L46), update to 1.17.
#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Nik-09** [comment]
Hi, @cpepper96 can you please assign this issue to me?
Thank you.

**Comment by durbi009** [comment]
I'd like to get started with Meshery! Please assign this issue to me @cpepper96 
Thank you

**Comment by cpepper96** [comment]
@durbi009 👍

**Comment by leecalcote** [comment]
excellent!

**Comment by aman-raza** [comment]
Hey, @cpepper96  I want to work on this issue, 
If this is still open, please assign this to me
Thank you

**Comment by leecalcote** [comment]
@durbi009 are you working on this issue?

**Comment by aman-raza** [comment]
I guess he is inactive

**Comment by Revolyssup** [comment]
This workflow has been removed and has to be replaced
