### ISSUE TITLE
Enhance build, lint and security checks in workflow

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery-consul#264]
#### Current Behavior

Currently we have a lint-build.yaml which only performs lint checks and tries to build the adapter. [this](https://github.com/meshery/meshery-consul/blob/master/.github/workflows/lint-build.yml)
#### Desired Behavior

We need other checks as well. Refer to [this one in istio adapter](https://github.com/meshery/meshery-istio/blob/master/.github/workflows/ci.yml)
#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by yash37158** [comment]
Please assign it to me

**Comment by yash37158** [comment]
I would like to work on this issue

**Comment by yash37158** [comment]
Thanks, I have one doubt, how to set up project in our local machine.

**Comment by leecalcote** [comment]
@yash37158, here you are - https://docs.meshery.io/project/contributing. Until you're building the project, I'll free your assignment from this issue so that other can carry it forward in the meantime.

**Comment by karnatisrinivas** [comment]
Hello @leecalcote , Can I would like to give it a try.

**Comment by leecalcote** [comment]
Sounds great, @karnatisrinivas
