### ISSUE TITLE
Permission issue in container

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery-consul#274]
#### Current Behavior

`mkdir /home/appuser/templates/oam/workloads/v0.44.0: permission denied`
#### Expected Behavior

Dockerfile should be improved to avoid such permission issue
#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v
- **Meshery Adapter Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by lumenCodes** [comment]
Hi @Revolyssup I am a first time contributor  and I don't have experience with docker. I don't know if this issue is something I can work on with maybe a few guidelines on how to go about it.

**Comment by lumenCodes** [comment]
Okay, thanks.

I will revert with my findings.

**Comment by yash37158** [comment]
Not sure, but consul Dockerfile is configured in reference to Mac or Linux-based system which is creating a permission issue .one possible solution can be configuring it as other mesh adapters.
