### ISSUE TITLE
CrashLoopBackOff while deploying meshery-consul

### ISSUE THREAD

**Issue by AugustasV** [meshery/meshery-consul#296]
#### Current Behavior

meshery-consul deployed to k8s throwing image CrashLoopBackOff error
```
Containers:
  meshery-consul:
    Container ID:   docker://d7fd75f94aacead0c79613f5cb78945d787f173f289f0b321efc5295877fc2eb
    Image:          layer5/meshery-consul:stable-latest
    Image ID:       docker-pullable://layer5/meshery-consul@sha256:7e3630f0ac0064521e8f0aa9d6c9aae0ef75670ab777d5c261ce0c04356f98cd
    Port:           10002/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    127
      Started:      Sun, 21 Aug 2022 21:23:34 +0200
      Finished:     Sun, 21 Aug 2022 21:23:34 +0200
```
```
k logs meshery-consul-8484fbcc96-s4xlt -n meshery
/bin/sh: ./meshery-consul: not found
```
same error appears than running and building locally too.
#### Expected Behavior

Pod deployed and running properly
#### Environment

- **Host OS:** Mac m1
- **Platform:** Kubernetes 1.24
- **Meshery Server Version:** stable-v0.6.0-rc.6fd
- **Meshery Client Version:** 
- **Meshery Adapter Version:** stable-latest, tried with edge version too.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Yh010** [comment]
I suppose, the binary , meshery-consul is missing. Did you check whether the binary was built correctly? After building the binary using 
```
./build.sh

```
or

```
go build -o meshery-consul

```

the binary should be present either in  /build directory or in the /home/appuser directory, else you will get the CrashLoopBackOff error
