### ISSUE TITLE
[Readme] Consistently present Meshery logo

### ISSUE THREAD

**Issue by legendarykamal** [meshery/meshery-consul#313]
#### Current State

The logo in the readme is not consistent with the one in meshery/meshery repo make it consistent :)

#### Desired State

Also check it even in the dark mode , make sure its consistent.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
adding -> meshery's logo is bigger in size in this readme.

**Comment by nishantn31** [comment]
Can I work on this?
