### ISSUE TITLE
[Lint] Refactor `.golangci.yml`

### ISSUE THREAD

**Issue by acald-creator** [meshery/meshery-consul#330]
#### Current Behavior
Sometimes when I run `golangci-lint`, there are inaccurate or incomplete report of the things that could be enhance in the Go files.

#### Desired Behavior
Would like to propose to update the `.golangci.yml` file to latest and remove deprecated checks, and add new checks if there are any available.

#### Implementation
I will be submitting a PR with a newer `.golangci.yml` config file with fewer and/or more settings. We can change as needed.

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Sounds like a great plan to me. ✔️

**Comment by acald-creator** [comment]
bump

Still working on this
