### ISSUE TITLE
Consul not running

### ISSUE THREAD

**Issue by acald-creator** [meshery/meshery-consul#361]
#### Current Behavior

```bash
docker logs meshery-consul
invalid argument
time="2023-02-17T01:30:41Z" level=error msg="Config File \"consul\" Not Found in \"[/root/.meshery]\"" app=consul-adapter code=11056 probable-cause="Viper is crashing" severity=4 short-description="Viper configuration initialization failed" suggested-remediation="Make sure viper is configured properly"
```

I was testing out `mesheryctl` and noticed that the Consul adapter was not coming up. Looks like there's an issue with Consul starting up via Docker.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v
- **Meshery Adapter Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Revolyssup** [comment]
Fixed by https://github.com/meshery/meshery-consul/pull/362
